// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------ //
// cec_rx //
// ------ //

#define cec_rx_wrap_target 0
#define cec_rx_wrap 28
#define cec_rx_pio_version 0

#define cec_rx_CEC_RX_RATE_HZ 20000

static const uint16_t cec_rx_program_instructions[] = {
            //     .wrap_target
    0x20a0, //  0: wait   1 pin, 0
    0x2020, //  1: wait   0 pin, 0
    0xe03f, //  2: set    x, 31
    0x00c0, //  3: jmp    pin, 0
    0x0043, //  4: jmp    x--, 3
    0x20a0, //  5: wait   1 pin, 0
    0xa0c3, //  6: mov    isr, null
    0xe047, //  7: set    y, 7
    0x2020, //  8: wait   0 pin, 0
    0xe034, //  9: set    x, 20
    0x004a, // 10: jmp    x--, 10
    0x4001, // 11: in     pins, 1
    0x20a0, // 12: wait   1 pin, 0
    0x0088, // 13: jmp    y--, 8
    0x2020, // 14: wait   0 pin, 0
    0xe034, // 15: set    x, 20
    0x0050, // 16: jmp    x--, 16
    0x4001, // 17: in     pins, 1
    0x00d8, // 18: jmp    pin, 24
    0x20a0, // 19: wait   1 pin, 0
    0x2020, // 20: wait   0 pin, 0
    0x8020, // 21: push   block
    0x20a0, // 22: wait   1 pin, 0
    0x0006, // 23: jmp    6
    0x20a0, // 24: wait   1 pin, 0
    0x2020, // 25: wait   0 pin, 0
    0x8020, // 26: push   block
    0x20a0, // 27: wait   1 pin, 0
    0x0000, // 28: jmp    0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program cec_rx_program = {
    .instructions = cec_rx_program_instructions,
    .length = 29,
    .origin = -1,
    .pio_version = cec_rx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config cec_rx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + cec_rx_wrap_target, offset + cec_rx_wrap);
    return c;
}
#endif

