// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------ //
// cec_tx //
// ------ //

#define cec_tx_wrap_target 0
#define cec_tx_wrap 7
#define cec_tx_pio_version 0

#define cec_tx_CEC_TX_RATE_HZ 1000000

static const uint16_t cec_tx_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0xa027, //  1: mov    x, osr
    0xe081, //  2: set    pindirs, 1
    0x0043, //  3: jmp    x--, 3
    0x80a0, //  4: pull   block
    0xa027, //  5: mov    x, osr
    0xe080, //  6: set    pindirs, 0
    0x0047, //  7: jmp    x--, 7
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program cec_tx_program = {
    .instructions = cec_tx_program_instructions,
    .length = 8,
    .origin = -1,
    .pio_version = cec_tx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config cec_tx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + cec_tx_wrap_target, offset + cec_tx_wrap);
    return c;
}
#endif

