#ifndef PICOARC_USB_DESCRIPTORS_H
#define PICOARC_USB_DESCRIPTORS_H

#define UAC2_ENTITY_INPUT_TERMINAL      0x01
#define UAC2_ENTITY_FEATURE_UNIT        0x02
#define UAC2_ENTITY_OUTPUT_TERMINAL     0x03
#define UAC2_ENTITY_CLOCK               0x04

#define ITF_NUM_CDC                     0
#define ITF_NUM_CDC_DATA                1
#define ITF_NUM_AUDIO_CONTROL           2
#define ITF_NUM_AUDIO_STREAMING         3
#define ITF_NUM_RESET                   4
#define ITF_NUM_TOTAL                   5

// UAC2 streaming alts exposed on ITF_NUM_AUDIO_STREAMING. Alt 0 is the
// mandatory zero-bandwidth setting; alt 1 is 16-bit stereo PCM; alt 2 is
// 24-bit packed stereo PCM. Both alts run at whatever rate the host
// programs via SET CUR on the clock source (48 kHz or 96 kHz are advertised
// — see usb_audio.c clock_get_request).
#define PICOARC_AUDIO_ALT_ZERO          0
#define PICOARC_AUDIO_ALT_PCM_16        1
#define PICOARC_AUDIO_ALT_PCM_24        2

#define PICOARC_AUDIO_SAMPLE_RATE_LOW   48000
#define PICOARC_AUDIO_SAMPLE_RATE_HIGH  96000
#define PICOARC_AUDIO_CHANNELS          2
// EP wMaxPacketSize is sized for the highest sample rate the device advertises
// so a single ISO packet at 96 kHz fits. At lower rates the host simply
// transmits a smaller packet each microframe.
#define PICOARC_AUDIO_EP_OUT_SZ_16      TUD_AUDIO_EP_SIZE(PICOARC_AUDIO_SAMPLE_RATE_HIGH, 2, PICOARC_AUDIO_CHANNELS)
#define PICOARC_AUDIO_EP_OUT_SZ_24      TUD_AUDIO_EP_SIZE(PICOARC_AUDIO_SAMPLE_RATE_HIGH, 3, PICOARC_AUDIO_CHANNELS)

#define TUD_AUDIO_PICOARC_DESC_LEN (TUD_AUDIO_DESC_IAD_LEN\
    + TUD_AUDIO_DESC_STD_AC_LEN\
    + TUD_AUDIO_DESC_CS_AC_LEN\
    + TUD_AUDIO_DESC_CLK_SRC_LEN\
    + TUD_AUDIO_DESC_INPUT_TERM_LEN\
    + TUD_AUDIO_DESC_OUTPUT_TERM_LEN\
    + TUD_AUDIO_DESC_FEATURE_UNIT_TWO_CHANNEL_LEN\
    + TUD_AUDIO_DESC_STD_AC_INT_EP_LEN\
    + TUD_AUDIO_DESC_STD_AS_INT_LEN /* alt 0 */ \
    + TUD_AUDIO_DESC_STD_AS_INT_LEN /* alt 1 */ \
    + TUD_AUDIO_DESC_CS_AS_INT_LEN\
    + TUD_AUDIO_DESC_TYPE_I_FORMAT_LEN\
    + TUD_AUDIO_DESC_STD_AS_ISO_EP_LEN\
    + TUD_AUDIO_DESC_CS_AS_ISO_EP_LEN\
    + TUD_AUDIO_DESC_STD_AS_ISO_FB_EP_LEN\
    + TUD_AUDIO_DESC_STD_AS_INT_LEN /* alt 2 */ \
    + TUD_AUDIO_DESC_CS_AS_INT_LEN\
    + TUD_AUDIO_DESC_TYPE_I_FORMAT_LEN\
    + TUD_AUDIO_DESC_STD_AS_ISO_EP_LEN\
    + TUD_AUDIO_DESC_CS_AS_ISO_EP_LEN\
    + TUD_AUDIO_DESC_STD_AS_ISO_FB_EP_LEN)

#define TUD_AUDIO_PICOARC_DESCRIPTOR(_itfnum, _stridx, _epout, _epfb, _epfbsize, _epint) \
    TUD_AUDIO_DESC_IAD(_itfnum, 0x02, 0x00),\
    TUD_AUDIO_DESC_STD_AC(_itfnum, 0x01, _stridx),\
    TUD_AUDIO_DESC_CS_AC(0x0200, AUDIO_FUNC_DESKTOP_SPEAKER, TUD_AUDIO_DESC_CLK_SRC_LEN + TUD_AUDIO_DESC_INPUT_TERM_LEN + TUD_AUDIO_DESC_OUTPUT_TERM_LEN + TUD_AUDIO_DESC_FEATURE_UNIT_TWO_CHANNEL_LEN, AUDIO_CS_AS_INTERFACE_CTRL_LATENCY_POS),\
    TUD_AUDIO_DESC_CLK_SRC(UAC2_ENTITY_CLOCK, AUDIO_CLOCK_SOURCE_ATT_INT_PRO_CLK, AUDIO_CTRL_RW << AUDIO_CLOCK_SOURCE_CTRL_CLK_FRQ_POS, UAC2_ENTITY_INPUT_TERMINAL, 0x00),\
    TUD_AUDIO_DESC_INPUT_TERM(UAC2_ENTITY_INPUT_TERMINAL, AUDIO_TERM_TYPE_USB_STREAMING, 0x00, UAC2_ENTITY_CLOCK, 0x02, AUDIO_CHANNEL_CONFIG_NON_PREDEFINED, 0x00, 0x0000, 0x00),\
    TUD_AUDIO_DESC_OUTPUT_TERM(UAC2_ENTITY_OUTPUT_TERMINAL, AUDIO_TERM_TYPE_OUT_DESKTOP_SPEAKER, UAC2_ENTITY_INPUT_TERMINAL, UAC2_ENTITY_FEATURE_UNIT, UAC2_ENTITY_CLOCK, 0x0000, 0x00),\
    TUD_AUDIO_DESC_FEATURE_UNIT_TWO_CHANNEL(UAC2_ENTITY_FEATURE_UNIT, UAC2_ENTITY_INPUT_TERMINAL, AUDIO_CTRL_RW << AUDIO_FEATURE_UNIT_CTRL_MUTE_POS | AUDIO_CTRL_RW << AUDIO_FEATURE_UNIT_CTRL_VOLUME_POS, AUDIO_CTRL_RW << AUDIO_FEATURE_UNIT_CTRL_MUTE_POS | AUDIO_CTRL_RW << AUDIO_FEATURE_UNIT_CTRL_VOLUME_POS, AUDIO_CTRL_RW << AUDIO_FEATURE_UNIT_CTRL_MUTE_POS | AUDIO_CTRL_RW << AUDIO_FEATURE_UNIT_CTRL_VOLUME_POS, 0x00),\
    TUD_AUDIO_DESC_STD_AC_INT_EP(_epint, 0x01),\
    /* AS alt 0: zero-bandwidth (mandatory). */ \
    TUD_AUDIO_DESC_STD_AS_INT((uint8_t)((_itfnum) + 1), PICOARC_AUDIO_ALT_ZERO, 0x00, 0x00),\
    /* AS alt 1: 16-bit stereo PCM (rate from clock source). */ \
    TUD_AUDIO_DESC_STD_AS_INT((uint8_t)((_itfnum) + 1), PICOARC_AUDIO_ALT_PCM_16, 0x02, 0x00),\
    TUD_AUDIO_DESC_CS_AS_INT(UAC2_ENTITY_INPUT_TERMINAL, AUDIO_CTRL_NONE, AUDIO_FORMAT_TYPE_I, AUDIO_DATA_FORMAT_TYPE_I_PCM, 0x02, AUDIO_CHANNEL_CONFIG_NON_PREDEFINED, 0x00),\
    TUD_AUDIO_DESC_TYPE_I_FORMAT(2, 16),\
    TUD_AUDIO_DESC_STD_AS_ISO_EP(_epout, (uint8_t)(TUSB_XFER_ISOCHRONOUS | TUSB_ISO_EP_ATT_ASYNCHRONOUS | TUSB_ISO_EP_ATT_DATA), PICOARC_AUDIO_EP_OUT_SZ_16, 0x01),\
    TUD_AUDIO_DESC_CS_AS_ISO_EP(AUDIO_CS_AS_ISO_DATA_EP_ATT_NON_MAX_PACKETS_OK, AUDIO_CTRL_NONE, AUDIO_CS_AS_ISO_DATA_EP_LOCK_DELAY_UNIT_MILLISEC, 0x0001),\
    TUD_AUDIO_DESC_STD_AS_ISO_FB_EP(_epfb, _epfbsize, 0x01),\
    /* AS alt 2: 24-bit (packed, 3 bytes per sample) stereo PCM (rate from clock source). */ \
    TUD_AUDIO_DESC_STD_AS_INT((uint8_t)((_itfnum) + 1), PICOARC_AUDIO_ALT_PCM_24, 0x02, 0x00),\
    TUD_AUDIO_DESC_CS_AS_INT(UAC2_ENTITY_INPUT_TERMINAL, AUDIO_CTRL_NONE, AUDIO_FORMAT_TYPE_I, AUDIO_DATA_FORMAT_TYPE_I_PCM, 0x02, AUDIO_CHANNEL_CONFIG_NON_PREDEFINED, 0x00),\
    TUD_AUDIO_DESC_TYPE_I_FORMAT(3, 24),\
    TUD_AUDIO_DESC_STD_AS_ISO_EP(_epout, (uint8_t)(TUSB_XFER_ISOCHRONOUS | TUSB_ISO_EP_ATT_ASYNCHRONOUS | TUSB_ISO_EP_ATT_DATA), PICOARC_AUDIO_EP_OUT_SZ_24, 0x01),\
    TUD_AUDIO_DESC_CS_AS_ISO_EP(AUDIO_CS_AS_ISO_DATA_EP_ATT_NON_MAX_PACKETS_OK, AUDIO_CTRL_NONE, AUDIO_CS_AS_ISO_DATA_EP_LOCK_DELAY_UNIT_MILLISEC, 0x0001),\
    TUD_AUDIO_DESC_STD_AS_ISO_FB_EP(_epfb, _epfbsize, 0x01)

#endif
